apply plugin: 'java'

version = '4.0.4'
group = 'zsawyer.mods.mumblelink'
archivesBaseName = 'MumbleLink'
sourceCompatibility = '1.6'
targetCompatibility = '1.6'
ext.mcversion = '1.6.4'
ext.forgeversion = '9.11.0.897'

processResources {
    from(sourceSets.main.resources.srcDirs) {
        include '**/*.lang'
        include '**/*.info'
        include '**/*.txt'
        expand 'version': project.version,
                'mcversion': mcversion,
                'forgeversion': forgeversion,
                'date': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude '**/*.lang'
        exclude '**/*.info'
        exclude '**/*.txt'
    }
}

configurations {
    includeInJar
    compile.extendsFrom includeInJar
}

dependencies {
    // Minecraft 1.6.4 + Forge 9.11.0.897 API stubs for compilation only
    compile files('jars/mc-stubs.jar')
    // JNA is bundled into the final jar
    includeInJar files('jars/jna-4.0.0.jar')
}

jar {
    archiveName = 'MumbleLink-' + version + '.jar'
    from zipTree(configurations.includeInJar.singleFile)
    from zipTree('jars/natives.jar')
}
