buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'forge'
            url = 'http://files.minecraftforge.net/maven'
        }
        maven {
            name = 'sonatype'
            url = 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.1-SNAPSHOT'
    }
}

apply plugin: 'forge'

version = '4.0.4'
group = 'zsawyer.mods.mumblelink'
archivesBaseName = 'mumblelink'
sourceCompatibility = '1.6'
targetCompatibility = '1.6'
ext.mcversion = '1.6.4'
ext.forgeversion = '9.11.0.897'

minecraft {
    version = mcversion + '-' + forgeversion
    assetDir = 'eclipse/assets'
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        include '**/*.lang'
        include '**/*.info'
        include '**/*.txt'
        expand 'version': project.version,
                'mcversion': mcversion,
                'date': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude '**/*.lang'
        exclude '**/*.info'
        exclude '**/*.txt'
    }
}

configurations {
    includeInJar
}

dependencies {
    includeInJar 'net.java.dev.jna:jna:4.0.0'
    compile configurations.includeInJar
}

jar {
    from zipTree(configurations.includeInJar.singleFile)
    from zipTree('jars/natives.jar')
}
